# Generated by Django 6.0 on 2026-04-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('EDUCATOR', 'Educator'), ('INSTITUTION', 'Institution'), ('LEARNER', 'Student / Parent'), ('SUPER_ADMIN', 'Super Admin')], default='EDUCATOR', max_length=20),
        ),
    ]
