# Generated by Django 6.0 on 2025-12-28 19:50

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('institution_type', models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('COACHING', 'Coaching Center'), ('OTHER', 'Other')], default='SCHOOL', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='institutions/covers/')),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('student_count_range', models.CharField(blank=True, choices=[('1-100', '1-100'), ('101-500', '101-500'), ('501-1000', '501-1,000'), ('1001-5000', '1,001-5,000'), ('5001-10000', '5,001-10,000'), ('10000+', '10,000+')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_domain', models.CharField(blank=True, max_length=100)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='administered_institutions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_institutions', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='following_institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'db_table': 'institutions',
                'ordering': ['name'],
            },
        ),
    ]
