# Generated by Django 6.0 on 2025-12-30 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='city',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='country',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='state',
        ),
        migrations.AddField(
            model_name='institution',
            name='is_hiring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='notable_alumni',
            field=models.ManyToManyField(blank=True, help_text='Link to actual user profiles as notable alumni', related_name='notable_at_institutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('COACHING', 'Coaching Center'), ('EDTECH', 'EdTech Platform'), ('OTHER', 'Other')], default='SCHOOL', max_length=20),
        ),
        migrations.CreateModel(
            name='InstitutionAcademic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('levels_offered', models.JSONField(blank=True, default=list)),
                ('streams', models.JSONField(blank=True, default=list)),
                ('courses', models.JSONField(blank=True, default=list)),
                ('boards_affiliations', models.JSONField(blank=True, default=list)),
                ('medium_of_instruction', models.JSONField(blank=True, default=list)),
                ('teaching_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid')], default='OFFLINE', max_length=20)),
                ('accreditation_body', models.CharField(blank=True, max_length=200)),
                ('accreditation_grade', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_details', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Institution Academic',
                'db_table': 'institution_academics',
            },
        ),
        migrations.CreateModel(
            name='InstitutionContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('google_maps_embed_url', models.URLField(blank=True, help_text='Google Maps embed iframe URL')),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='e.g., {"monday": "9:00 AM - 5:00 PM", "saturday": "Closed"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Institution Contact',
                'db_table': 'institution_contacts',
            },
        ),
        migrations.CreateModel(
            name='InstitutionInfrastructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus_size', models.CharField(blank=True, help_text='e.g., "10 acres"', max_length=100)),
                ('total_classrooms', models.PositiveIntegerField(default=0)),
                ('total_labs', models.PositiveIntegerField(default=0)),
                ('has_library', models.BooleanField(default=False)),
                ('has_computer_lab', models.BooleanField(default=False)),
                ('has_science_lab', models.BooleanField(default=False)),
                ('has_sports_facility', models.BooleanField(default=False)),
                ('has_playground', models.BooleanField(default=False)),
                ('has_auditorium', models.BooleanField(default=False)),
                ('has_cafeteria', models.BooleanField(default=False)),
                ('has_hostel', models.BooleanField(default=False)),
                ('has_transport', models.BooleanField(default=False)),
                ('has_smart_class', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('other_facilities', models.TextField(blank=True, help_text='Comma-separated list of other facilities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_details', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Institution Infrastructure',
                'db_table': 'institution_infrastructure',
            },
        ),
        migrations.CreateModel(
            name='InstitutionSocial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('brochure_pdf', models.FileField(blank=True, null=True, upload_to='institutions/brochures/')),
                ('prospectus_pdf', models.FileField(blank=True, null=True, upload_to='institutions/prospectus/')),
                ('intro_video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_details', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Institution Social',
                'db_table': 'institution_social',
            },
        ),
        migrations.CreateModel(
            name='InstitutionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('relationship', models.CharField(choices=[('STUDENT', 'Student'), ('ALUMNI', 'Alumni'), ('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('OTHER', 'Other')], default='STUDENT', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='institutions.institution')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institution_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('institution', 'reviewer')},
            },
        ),
    ]
