# Generated by Django 6.0 on 2026-04-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
