# Generated by Django 6.0 on 2026-04-19 11:15

from django.db import migrations

def seed_categories(apps, schema_editor):
    ServiceCategory = apps.get_model('acadservices', 'ServiceCategory')
    ServiceCategory.objects.get_or_create(name='Curriculum Design', slug='curriculum-design', defaults={'description': 'Design and review of academic programs', 'icon': 'book-open'})
    ServiceCategory.objects.get_or_create(name='Mentoring & Coaching', slug='mentoring-coaching', defaults={'description': '1-on-1 guidance for students and educators', 'icon': 'graduation-cap'})
    ServiceCategory.objects.get_or_create(name='Workshop & Training', slug='workshop-training', defaults={'description': 'Host or lead academic workshops', 'icon': 'globe'})
    ServiceCategory.objects.get_or_create(name='Consulting', slug='consulting', defaults={'description': 'Expert advice on academic operations', 'icon': 'layout-grid'})

def reverse_seed(apps, schema_editor):
    ServiceCategory = apps.get_model('acadservices', 'ServiceCategory')
    ServiceCategory.objects.filter(slug__in=['curriculum-design', 'mentoring-coaching', 'workshop-training', 'consulting']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('acadservices', '0002_make_tagline_description_optional'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_seed),
    ]
