# Generated by Django 6.0 on 2026-03-06 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_lms_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='accreditation_body',
            field=models.CharField(blank=True, help_text='Certifying body (e.g., CBSE, Microsoft Educator, NCERT)', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='accreditation_logo',
            field=models.ImageField(blank=True, null=True, upload_to='accreditations/'),
        ),
        migrations.AddField(
            model_name='course',
            name='bulk_price_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price per seat for bulk purchases', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_fdp',
            field=models.BooleanField(default=True, help_text='Mark as Faculty Development Program'),
        ),
        migrations.AddField(
            model_name='course',
            name='min_bulk_seats',
            field=models.PositiveIntegerField(default=5, help_text='Minimum seats for bulk pricing'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.JSONField(blank=True, default=list, help_text='Target audience categories'),
        ),
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='Topics covered'),
        ),
        migrations.AddField(
            model_name='course',
            name='validity_period_months',
            field=models.PositiveIntegerField(choices=[(0, 'Lifetime'), (12, '1 Year'), (24, '2 Years'), (36, '3 Years'), (60, '5 Years')], default=0, help_text='Certificate validity period (0 = lifetime)'),
        ),
        migrations.CreateModel(
            name='BulkPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seats_purchased', models.PositiveIntegerField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_purchases', to='courses.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_purchases',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_codes', to='courses.bulkpurchase')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_code', to='courses.enrollment')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'redemption_codes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fdp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fdp_bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'fdp')},
            },
        ),
    ]
