# Generated by Django 6.0 on 2026-03-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_bookmark_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_public',
            field=models.BooleanField(default=True, help_text='User can hide certificate from profile'),
        ),
    ]
