# Generated by Django 6.0 on 2025-12-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='user_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
