# Generated by Django 6.0 on 2025-12-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_user_note_to_savedjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-is_urgent', '-created_at']},
        ),
        migrations.AddField(
            model_name='joblisting',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Mark as urgent hiring'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_category',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('GUEST', 'Guest Lecturer'), ('INVIGILATOR', 'Exam Invigilator'), ('CONTENT', 'Content Creator'), ('TUTOR', 'Private Tutor'), ('SUBSTITUTE', 'Substitute Teacher')], default='PERMANENT', max_length=20),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_level',
            field=models.CharField(blank=True, choices=[('PRT', 'Primary Teacher (PRT)'), ('TGT', 'Trained Graduate Teacher (TGT)'), ('PGT', 'Post Graduate Teacher (PGT)'), ('LECTURER', 'Lecturer'), ('HOD', 'Head of Department'), ('COORDINATOR', 'Academic Coordinator'), ('PRINCIPAL', 'Principal/Vice Principal'), ('ADMIN', 'Administrative Staff'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='min_qualification',
            field=models.CharField(choices=[('B_ED', 'B.Ed'), ('M_ED', 'M.Ed'), ('M_PHIL', 'M.Phil'), ('PHD', 'PhD'), ('D_ED', 'D.Ed'), ('NTT', 'NTT'), ('GRADUATE', 'Graduate'), ('POST_GRADUATE', 'Post Graduate'), ('ANY', 'Any')], default='ANY', max_length=20),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='perks',
            field=models.JSONField(default=list, help_text='Benefits offered'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='positions_available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='required_board_experience',
            field=models.JSONField(default=list, help_text='Required board experience'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='subject_specialization',
            field=models.JSONField(default=list, help_text='Required subject expertise'),
        ),
    ]
