# Generated by Django 6.0 on 2025-12-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/institutions/backgrounds/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/teachers/backgrounds/'),
        ),
    ]
