# Generated by Django 6.0 on 2025-12-28 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('profiles', '0003_add_linkedin_profile_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_education', to='institutions.institution'),
        ),
    ]
