# Generated by Django 6.0 on 2025-12-30 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_education_graduation_year_education_school_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('who_can_send_connect_request', models.CharField(choices=[('PUBLIC', 'Everyone'), ('CONNECTIONS_ONLY', 'Connections Only'), ('NO_ONE', 'Only Me')], default='PUBLIC', max_length=20)),
                ('who_can_see_connections_list', models.CharField(choices=[('PUBLIC', 'Everyone'), ('CONNECTIONS_ONLY', 'Connections Only'), ('NO_ONE', 'Only Me')], default='CONNECTIONS_ONLY', max_length=20)),
                ('who_can_see_posts', models.CharField(choices=[('PUBLIC', 'Everyone'), ('CONNECTIONS_ONLY', 'Connections Only'), ('NO_ONE', 'Only Me')], default='PUBLIC', max_length=20)),
                ('who_can_see_email', models.CharField(choices=[('PUBLIC', 'Everyone'), ('CONNECTIONS_ONLY', 'Connections Only'), ('NO_ONE', 'Only Me')], default='CONNECTIONS_ONLY', max_length=20)),
                ('who_can_see_phone', models.CharField(choices=[('PUBLIC', 'Everyone'), ('CONNECTIONS_ONLY', 'Connections Only'), ('NO_ONE', 'Only Me')], default='CONNECTIONS_ONLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Privacy Settings',
                'verbose_name_plural': 'User Privacy Settings',
                'db_table': 'user_privacy_settings',
            },
        ),
    ]
