# Generated by Django 6.0 on 2025-12-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_add_privacy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('FREELANCE', 'Freelance'), ('OCCUPIED', 'Not Available')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='boards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='demo_video_file',
            field=models.FileField(blank=True, help_text='MP4 or MOV, max 50MB', null=True, upload_to='demo_videos/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo link'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='grades_taught',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_modes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
