# Generated by Django 6.0 on 2026-03-07
#
# Migration notes:
# - EducatorProfile is a RENAME of TeacherProfile (Python-level alias in models.py).
#   The underlying DB table is still 'teacher_profiles' — no schema change needed.
#   We use SeparateDatabaseAndState to update only Django's migration state.
# - Endorsement is a brand-new model that DOES need a CREATE TABLE.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_modular_models'),
        ('profiles', '0007_add_educator_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── State-only rename: TeacherProfile ➜ EducatorProfile ──────────────
        # The physical table (teacher_profiles) is unchanged; we only update
        # Django's internal model registry so FK references resolve correctly.
        migrations.SeparateDatabaseAndState(
            database_operations=[],   # no DDL changes needed
            state_operations=[
                migrations.CreateModel(
                    name='EducatorProfile',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('first_name', models.CharField(blank=True, max_length=100)),
                        ('last_name', models.CharField(blank=True, max_length=100)),
                        ('headline', models.CharField(blank=True, max_length=200)),
                        ('bio', models.TextField(blank=True)),
                        ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/educators/')),
                        ('background_photo', models.ImageField(blank=True, null=True, upload_to='profiles/educators/backgrounds/')),
                        ('current_role', models.CharField(blank=True, max_length=50)),
                        ('current_role_custom', models.CharField(blank=True, max_length=100)),
                        ('experience_years', models.PositiveIntegerField(default=0)),
                        ('current_school', models.CharField(blank=True, max_length=200)),
                        ('qualifications', models.JSONField(blank=True, default=list)),
                        ('open_to_work', models.BooleanField(default=True)),
                        ('education', models.JSONField(blank=True, default=list)),
                        ('certifications', models.JSONField(blank=True, default=list)),
                        ('skills', models.JSONField(blank=True, default=list)),
                        ('expert_subjects', models.JSONField(default=list)),
                        ('subjects', models.JSONField(blank=True, default=list)),
                        ('availability', models.CharField(blank=True, default='AVAILABLE', max_length=20)),
                        ('teaching_modes', models.JSONField(blank=True, default=list)),
                        ('boards', models.JSONField(blank=True, default=list)),
                        ('grades_taught', models.JSONField(blank=True, default=list)),
                        ('demo_video_url', models.URLField(blank=True)),
                        ('demo_video_file', models.FileField(blank=True, null=True, upload_to='demo_videos/')),
                        ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                        ('portfolio_url', models.URLField(blank=True)),
                        ('linkedin_url', models.URLField(blank=True)),
                        ('phone', models.CharField(blank=True, max_length=20)),
                        ('city', models.CharField(blank=True, max_length=100)),
                        ('state', models.CharField(blank=True, max_length=100)),
                        ('is_searchable', models.BooleanField(default=True)),
                        ('contact_visible', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('current_institution', models.ForeignKey(
                            blank=True, null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            related_name='current_educators',
                            to='institutions.institution',
                        )),
                        ('user', models.OneToOneField(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='educator_profile',
                            to=settings.AUTH_USER_MODEL,
                        )),
                    ],
                    options={
                        'verbose_name': 'Educator Profile',
                        'verbose_name_plural': 'Educator Profiles',
                        'db_table': 'teacher_profiles',
                    },
                ),
                # Re-point FKs from teacherprofile → educatorprofile (state only)
                migrations.AlterField(
                    model_name='certification',
                    name='profile',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='certification_entries',
                        to='profiles.educatorprofile',
                    ),
                ),
                migrations.AlterField(
                    model_name='education',
                    name='profile',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='education_entries',
                        to='profiles.educatorprofile',
                    ),
                ),
                migrations.AlterField(
                    model_name='experience',
                    name='profile',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='experiences',
                        to='profiles.educatorprofile',
                    ),
                ),
                migrations.AlterField(
                    model_name='skill',
                    name='profile',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='skill_entries',
                        to='profiles.educatorprofile',
                    ),
                ),
                migrations.DeleteModel(name='TeacherProfile'),
            ],
        ),

        # ── Real DDL: Create skill_endorsements table ─────────────────────────
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endorser', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='given_endorsements',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('skill', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='endorsements',
                    to='profiles.skill',
                )),
            ],
            options={
                'verbose_name': 'Endorsement',
                'verbose_name_plural': 'Endorsements',
                'db_table': 'skill_endorsements',
                'ordering': ['created_at'],
                'unique_together': {('skill', 'endorser')},
            },
        ),
    ]
