# Generated by Django 6.0 on 2026-03-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_endorsement_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educatorprofile',
            old_name='current_school',
            new_name='current_institution_name',
        ),
        migrations.RenameField(
            model_name='educatorprofile',
            old_name='bio',
            new_name='notable_student_outcomes',
        ),
        migrations.AddField(
            model_name='educatorprofile',
            name='available_for',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='educatorprofile',
            name='awards_and_recognitions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='educatorprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='educatorprofile',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='educatorprofile',
            name='teaching_philosophy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='educatorprofile',
            name='time_availability',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('FULL_TIME', 'Open to Full-Time'), ('PART_TIME', 'Open to Part-Time'), ('FREELANCE', 'Freelance/Guest Lectures'), ('NOT_LOOKING', 'Not Looking')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='current_role',
            field=models.CharField(blank=True, choices=[('PRT', 'Primary Teacher (PRT)'), ('TGT', 'Trained Graduate Teacher (TGT)'), ('PGT', 'Post Graduate Teacher (PGT)'), ('LECTURER', 'Lecturer'), ('PROFESSOR', 'Professor'), ('HOD', 'Head of Department'), ('PRINCIPAL', 'Principal/Vice Principal'), ('COORDINATOR', 'Academic Coordinator'), ('TRAINER', 'Corporate Trainer'), ('COUNSELOR', 'Counselor'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='current_role_custom',
            field=models.CharField(blank=True, help_text='Custom role if Other selected', max_length=100),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='demo_video_file',
            field=models.FileField(blank=True, help_text='MP4 or MOV, max 50MB', null=True, upload_to='demo_videos/'),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo link'),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='expert_subjects',
            field=models.JSONField(default=list, help_text='Primary teaching subjects - at least one required'),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AlterField(
            model_name='educatorprofile',
            name='open_to_work',
            field=models.BooleanField(default=True, help_text='Show "Open to Work" badge'),
        ),
    ]
