# Generated by Django 6.0 on 2026-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_current_school_educatorprofile_current_institution_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educatorprofile',
            name='willing_to_collaborate_with',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
