# Generated by Django 6.0 on 2026-03-20 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_educatorprofile_willing_to_collaborate_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='accreditation_bodies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='accreditation_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='advertisement_interest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='alumni_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='app_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='average_annual_admissions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='awards_recognitions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='boards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='category_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='collaboration_interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='corporate_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='courses_offered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='data_source',
            field=models.CharField(default='Self-Registered', max_length=50),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='education_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='engagement_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='fee_range',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('PREMIUM', 'Premium')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='franchise_opportunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='google_maps_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='hiring_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='institution_usp',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='last_accreditation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='lead_potential_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='medium_of_instruction',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='mode_of_delivery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='naac_nba_score',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='notable_alumni',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('GOVERNMENT', 'Government'), ('TRUST', 'Trust'), ('SOCIETY', 'Society'), ('CORPORATE', 'Corporate'), ('PPP', 'PPP')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='pan_cin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='pass_percentage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='placement_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='placement_partners',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='poc_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='poc_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='portal_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='profile_completion_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='rankings_nirf',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='rankings_private',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='rankings_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='scholarships_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='streams',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='sub_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='top_recruiters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='total_non_teaching_staff',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='total_teaching_staff',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='vendor_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='vision_mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='visiting_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='institution_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('COACHING', 'Coaching Center'), ('TRAINING', 'Training Institute'), ('EDTECH', 'EdTech'), ('NGO', 'NGO'), ('CORPORATE_TRAINING', 'Corporate Training'), ('RESEARCH', 'Research'), ('OTHER', 'Other')], default='SCHOOL', max_length=50),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='InstitutionCampus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus_name', models.CharField(max_length=200)),
                ('campus_code', models.CharField(blank=True, max_length=100)),
                ('campus_type', models.CharField(choices=[('MAIN', 'Main'), ('BRANCH', 'Branch'), ('FRANCHISE', 'Franchise'), ('STUDY_CENTER', 'Study Center')], default='MAIN', max_length=50)),
                ('year_of_start', models.PositiveIntegerField(blank=True, null=True)),
                ('campus_status', models.CharField(choices=[('ACTIVE', 'Active'), ('UPCOMING', 'Upcoming'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=50)),
                ('full_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('urban_status', models.CharField(blank=True, choices=[('URBAN', 'Urban'), ('SEMI_URBAN', 'Semi-Urban'), ('RURAL', 'Rural')], max_length=50)),
                ('campus_area', models.CharField(blank=True, help_text='e.g. 10 acres', max_length=100)),
                ('classrooms_count', models.PositiveIntegerField(blank=True, null=True)),
                ('labs_available', models.BooleanField(default=False)),
                ('library_available', models.BooleanField(default=False)),
                ('hostel_type', models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('BOTH', 'Both'), ('NONE', 'None')], default='NONE', max_length=50)),
                ('sports_facilities', models.JSONField(blank=True, default=list)),
                ('transport_facility', models.BooleanField(default=False)),
                ('smart_classrooms', models.BooleanField(default=False)),
                ('courses_offered', models.JSONField(blank=True, default=list)),
                ('student_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('current_student_strength', models.PositiveIntegerField(blank=True, null=True)),
                ('faculty_count', models.PositiveIntegerField(blank=True, null=True)),
                ('student_teacher_ratio', models.CharField(blank=True, max_length=50)),
                ('medium_of_instruction', models.JSONField(blank=True, default=list)),
                ('shift_details', models.JSONField(blank=True, default=list)),
                ('campus_email', models.EmailField(blank=True, max_length=254)),
                ('campus_phone', models.CharField(blank=True, max_length=20)),
                ('campus_head_name', models.CharField(blank=True, max_length=100)),
                ('campus_head_designation', models.CharField(blank=True, max_length=100)),
                ('campus_whatsapp', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='profiles.institutionprofile')),
            ],
            options={
                'verbose_name': 'Institution Campus',
                'verbose_name_plural': 'Institution Campuses',
                'db_table': 'profiles_institution_campuses',
            },
        ),
        migrations.CreateModel(
            name='InstitutionCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(blank=True, help_text='e.g. 4 years, 6 months', max_length=100)),
                ('level', models.CharField(blank=True, help_text='e.g. UG, PG, Diploma', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campuses', models.ManyToManyField(blank=True, related_name='detailed_courses', to='profiles.institutioncampus')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_courses', to='profiles.institutionprofile')),
            ],
            options={
                'verbose_name': 'Institution Course',
                'verbose_name_plural': 'Institution Courses',
                'db_table': 'profiles_institution_courses',
            },
        ),
    ]
