# Generated by Django 6.0 on 2026-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_institutionprofile_accreditation_bodies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='campus_area',
            field=models.CharField(blank=True, help_text='e.g. 10 acres', max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='classrooms_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='current_student_strength',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='faculty_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='hostel_type',
            field=models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('BOTH', 'Both'), ('NONE', 'None')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='labs_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='library_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='shift_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='smart_classrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='sports_facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='student_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='student_teacher_ratio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='transport_facility',
            field=models.BooleanField(default=False),
        ),
    ]
