# Generated by Django 6.0 on 2026-03-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_educatorprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='govt_approvals',
            field=models.BooleanField(default=False),
        ),
    ]
