# Generated by Django 6.0 on 2026-03-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_institutionprofile_govt_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='educatorprofile',
            name='google_avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
